### ISSUE TITLE
Python  3.6 runtime error on hyperneat line 86

### ISSUE THREAD

**Issue by ai-nick** [noio/peas#6]
conns = filter(lambda (fr, to): np.all(np.abs(self.nodes[fr] - self.nodes[to]) <=  max_length), conns)
                          ^
SyntaxError: invalid syntax

**Comment by ai-nick** [comment]
ran into this error just now, will try to patch and submit for pull request before work, btw love this lib

**Comment by noio** [comment]
Hey Nick! Thanks for the patches. Not sure if I can verify their correctness, but if you say your pull request is done and is compatible with python 3, I'll give the whole thing a look and merge it.

**Comment by ai-nick** [comment]
Hey I"m pretty sure I'll double check again and let you know when, don't want to make you review more than necessary!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
